Chore: bulk deps
go-vela/vela-git pull request #147
Opened 2023-12-08 20:06 UTC by claire1618

2023-12-08 20:20 UTC, timhuynh94 submitted a review, later dismissed

2023-12-08 21:22 UTC, wass3rw3rk approved these changes

2023-12-08 21:23 UTC, wass3rw3rk requested changes

2023-12-08 21:23 UTC, wass3rw3rk commented on Dockerfile
> +FROM alpine@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48 as certs
version please :)

2023-12-08 21:23 UTC, wass3rw3rk commented on Dockerfile
> +FROM alpine:latest@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48
version please :)

2023-12-08 21:32 UTC, wass3rw3rk approved these changes

2023-12-11 15:06 UTC, ecrupper approved these changes

2023-12-11 17:28 UTC, merged